# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkgsearch', '0002_subpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpkgs', to='pkgsearch.Package'),
        ),
    ]
