# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkgsearch', '0003_auto_20181019_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default='no description', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='icon',
            field=models.CharField(default='package_128x128.png', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='summary',
            field=models.TextField(default='no summary', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='upstream_url',
            field=models.CharField(default='no url', max_length=150, null=True),
        ),
    ]
