# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkgsearch', '0004_auto_20181113_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpackage',
            name='icon',
        ),
        migrations.AlterField(
            model_name='subpackage',
            name='description',
            field=models.TextField(default='no description', null=True),
        ),
        migrations.AlterField(
            model_name='subpackage',
            name='summary',
            field=models.TextField(default='no summary', null=True),
        ),
    ]
