# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 09:00
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkgsearch', '0005_auto_20181114_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
