# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 09:27
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkgsearch', '0006_package_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='pkgsearch_p_search__128300_gin'),
        ),
    ]
